### ISSUE TITLE
How to pass multiple kaniko args ?

### ISSUE THREAD

**Issue by Mokto** [int128/kaniko-action#455]
I tried:

```
        kaniko-args:
          --use-new-run
          --compressed-caching=false
```

```
        kaniko-args: --use-new-run --compressed-caching=false
```

It unfortunately doesn't work

<img width="460" alt="image" src="https://github.com/int128/kaniko-action/assets/5103928/44df23d1-12f1-478c-8f56-a2f90d14999c">

Thanks!

**Comment by amartopoulos** [comment]
Hi, could this syntax be added to the documentation?  I ran into the same issue for the tags field and it took me a long time to find this bug report after trying every other syntax possible.   Thanks.
