### ISSUE TITLE
How to authenticate via docker json file ?

### ISSUE THREAD

**Issue by Proger666** [int128/kaniko-action#84]
Hello.
trying to authenticate according to the example but got:
` /kaniko/.docker/config.json: read /kaniko/.docker/config.json: is a directory
`
How to push dockerconfig for auth to the runner so kaniko can mount it ?

**Comment by int128** [comment]
This action passes `~/.docker/config.json` to the kaniko container.
Please check if it exists.

**Comment by Jerome1337** [comment]
Is have the same issue, the `config.json` is existing but when docker mount it, it becomes a folder.

Here is a cat of the content before kaniko action is started

```
{
	"auths": {
		"europe-docker.pkg.dev": {
			"auth": "***"
		}
	}
}
```

Then during the build I have this error

```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "europe-docker.pkg.dev/***/docker/***": resolving authorization for europe-docker.pkg.dev failed: /kaniko/.docker/config.json: read /kaniko/.docker/config.json: is a directory
```

The volume looks good: `-v /home/runner/.docker/config.json:/kaniko/.docker/config.json:ro`

Every seems fine but I still have this issue.

FYI, I'm login into GAR using the `docker/login-action@v2` action and login is successful.
